# RefereeBox‚©‚ç‘—‚ç‚ê‚Ä‚­‚écommand‚Ì’l
# default commands
COMM_STOP = 'STOP'
COMM_START = 'START'
COMM_WELCOME = 'WELCOME'  # NEW 2015CAMBADA: welcome message
COMM_RESET = 'RESET'  # NEW 2015CAMBADA: Reset Game
COMM_TESTMODE_ON = 'TESTMODE_ON'  # NEW 2015CAMBADA: TestMode On
COMM_TESTMODE_OFF = 'TESTMODE_OFF'  # NEW 2015CAMBADA: TestMode Off

# penalty Commands 
COMM_YELLOW_CARD = 'YELLOW_CARD' # NEW 2015CAMBADA: @remote
COMM_RED_CARD = 'RED_CARD' # NEW 2015CAMBADA: @remote
COMM_DOUBLE_YELLOW = 'DOUBLE_YELLOW' # NEW 2015CAMBADA: exits field

# game flow commands
COMM_FIRST_HALF = 'FIRST_HALF'
COMM_SECOND_HALF = 'SECOND_HALF'
COMM_FIRST_HALF_OVERTIME = 'FIRST_HALF_OVERTIME'  # NEW 2015CAMBADA: 
COMM_SECOND_HALF_OVERTIME = 'SECOND_HALF_OVERTIME'  # NEW 2015CAMBADA: 
COMM_HALF_TIME = 'HALF_TIME'
COMM_END_GAME = 'END_GAME'    # ends 2nd part, may go into overtime
COMM_END_PART = 'END_PART'    # ends 2nd part, may go into overtime
COMM_GAMEOVER = 'GAMEOVER'  # NEW 2015CAMBADA: Game Over
COMM_PARK = 'PARK'

# goal status
COMM_GOAL = 'GOAL'
COMM_SUBGOAL = 'SUBGOAL'

# game flow commands
COMM_KICKOFF = 'KICKOFF'
COMM_FREEKICK = 'FREEKICK'
COMM_GOALKICK = 'GOALKICK'
COMM_THROWIN = 'THROWIN'
COMM_CORNER = 'CORNER'
COMM_PENALTY = 'PENALTY'
COMM_DROP_BALL = 'DROP_BALL'

// specific team Commands
COMM_REPAIR = 'REPAIR'
COMM_REPAIR_END = 'REPAIR_END'
COMM_SUBSTITUTION = 'SUBSTITUTION'
COMM_ISALIVE = 'IS_ALIVE'

